### ISSUE TITLE
navigation arrows for non-event navigation

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#122]
Currently the navigation arrows forward and backwards only appear if the user has selected an event that provides a linear pathway through the material. However, if a particular section only has one edge leading away from it or to it, there is no reason not to include these arrows, or to have multiple arrows indicating different pathways

Another option might be to have a "mini-map" of the current course that users can click on to jump to other sections of a course

**Comment by alasdairwilson** [comment]
closed as completed via #162
