### ISSUE TITLE
Multiple paragraphs look cramped

### ISSUE THREAD

**Issue by smangham** [OxfordRSE/gutenberg#131]
Currently, it looks like Gutenberg removes multiple line breaks in sequence, leading to cramped text.

For example [from here](https://train.oxrse.uk/material/software_project_management/continuous_integration),
```
## How do we do it?

There are many CI infrastructures and services, free and paid for, and subject to change as they evolve their features.

In this course you will be using [GitHub Actions](https://github.com/features/actions), which unsurprisingly is available as part of GitHub.

There are other free options, for instance [Travis CI](https://travis-ci.com/) and [AppVeyor](https://www.appveyor.com/).
All three of these make use of common features across many CI implementations, and you are certainly advised to look at the options to see some of the commonalities and differences in how features are typically provided.
```
Renders to
> ## How do we do it?
>There are many CI infrastructures and services, free and paid for, and subject to change as they evolve their features.
> In this course you will be using [GitHub Actions](https://github.com/features/actions), which unsurprisingly is available as part of GitHub.
>There are other free options, for instance [Travis CI](https://travis-ci.com/) and [AppVeyor](https://www.appveyor.com/).
All three of these make use of common features across many CI implementations, and you are certainly advised to look at the options to see some of the commonalities and differences in how features are typically provided.

For readability, I'd expect it to look like this:
> ## How do we do it?
>There are many CI infrastructures and services, free and paid for, and subject to change as they evolve their features.
>
> In this course you will be using [GitHub Actions](https://github.com/features/actions), which unsurprisingly is available as part of GitHub.
>
>There are other free options, for instance [Travis CI](https://travis-ci.com/) and [AppVeyor](https://www.appveyor.com/).
All three of these make use of common features across many CI implementations, and you are certainly advised to look at the options to see some of the commonalities and differences in how features are typically provided.

Either preserving the newlines, or having extra vertical spacing between subsequent paragraphs.

**Comment by alasdairwilson** [comment]
Would you be happy with this spacing?

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/6ebee2d2-baf2-4548-9ed3-b3a4bbe80fb2)
