### ISSUE TITLE
Site-specific config missing page title option

### ISSUE THREAD

**Issue by steve-crouch** [OxfordRSE/gutenberg#170]
The content page title looks to be hardcoded to "OxRSE Training" in components/Header.tsx (https://github.com/steve-crouch/gutenberg/blob/main/components/Header.tsx). Could this be made a configurable option?

**Comment by martinjrobins** [comment]
we were just saying that this morning :) Agree it should be configurable. We also were talking about putting a logo somewhere obvious on each page (ie.. either oxford of southampton logo), and in the longer term a configurable theme so we can style things differently. At the moment our two pages look very similar!
