### ISSUE TITLE
Focus order can be confusing, when using the keyboard to navigate a page

### ISSUE THREAD

**Issue by eatyourgreens** [OxfordRSE/gutenberg#195]
Here, I'm using Tab to quickly navigate through the page. The tab order doesn't follow the layout on the page, and it isn't always obvious where keyboard focus currently is.

[WCAG 2 Success Criterion 2.4.3: Focus order](https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html).

https://github.com/OxfordRSE/gutenberg/assets/59547/48b6fd20-3e35-4653-86a7-0d04d9827392

**Comment by eatyourgreens** [comment]
Accessibility Insights for Chrome includes a tool to record the tab stops on the page. Here's a video of the tab stops in numbered order.


https://github.com/OxfordRSE/gutenberg/assets/59547/bb657fde-e02e-40b6-8a46-4fcaf5ec02d8

**Comment by alasdairwilson** [comment]
We have room to fix these but for accesibility these have been replaced entirely as the default way to navigate material by #238

**Comment by eatyourgreens** [comment]
Those new navigation blocks look good!
