### ISSUE TITLE
Adding multiple items to course page

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/gutenberg#212]
Currently, it's a slow and tedious process to add items to event groups.

![image](https://github.com/OxfordRSE/gutenberg/assets/3770306/a3620619-0ca1-4654-bc85-a0179bab4016)

You need to scroll through the list and add each item one by one.

Could we do one or more of the following:

1. Filter the list (e.g. type "- Testing -" and have it display only the matching items)
2. Add multiple, perhaps having items in the list as tickboxes
3. If you add a top level e.g. "HPCu - Technology and Tooling - Testing" it would by default add everything underneath

Happy to hear other ideas if there are better/easier suggestions!

**Comment by alasdairwilson** [comment]
I like 1. and 2. and I think doing both together works and would make this close to ideal (type theme + course name and click them all) but 3. probably isn't ideal as often there is a cpp + python track in the same course.

Will definitely sort this, I think we don't even need a tickbox but instead just keep the dropdown open so more can be clicked, with the clicked item removed or maybe even highlighted so it can be unselected. 

I bet there is a near out-of-the-box solution as well to a filterable dropdown.
