### ISSUE TITLE
learning objectives

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#223]
We've got a large number of learning objectives to incorporate into the course material, but still need a way to render these in the material. I've added in some test learning objectives into the proceedural programming course (https://github.com/UNIVERSE-HPC/course-material/pull/106), can use these to test.

- [ ] add learning objectives to the top of every section (if they exist)
- [ ] anywhere else that is useful (e.g. navigation graph? course page?)

**Comment by alasdairwilson** [comment]
This already exists (from #202 ) but we called the attribute learningoutcomes:

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/d1be3bd4-14fe-41e5-bc11-59414b38c5ec)

**Comment by martinjrobins** [comment]
sorry, forgot about this. happy to close then. Agree that the styling could use some improvements, but that can be another issue
