### ISSUE TITLE
Formatting of heading text wrapped in backticks

### ISSUE THREAD

**Issue by OllyK** [OxfordRSE/gutenberg#260]
The display of inline code snippets wrapped in backticks seems a little funky. For example the heading ```## Why Run Pytest Using `python -m` and Not `pytest` ?``` is displayed as shown in the image below. This is within a callout block, which may also be related.
![image](https://github.com/user-attachments/assets/a7ad2244-5650-405f-af53-f2639bf544a9)

**Comment by OllyK** [comment]
Another example here, also in a callout block
![image](https://github.com/user-attachments/assets/071c1ff9-944e-4c63-9c09-ef02d5cdaf56)

**Comment by alasdairwilson** [comment]
I cant recreate this at all either on the live site or locally, all headings render correctly for me across all the browsers so I am closing this for now.
