### ISSUE TITLE
Add set of basic step-by-step notes for a typical deployment

### ISSUE THREAD

**Issue by steve-crouch** [OxfordRSE/gutenberg#57]
As part of the Aug 2023 pilot, I've recorded some notes on deployment to Ubuntu 22.04 that we can convert to markdown as a basic guide.

**Comment by martinjrobins** [comment]
fantastic :) if you could include these as some sort of installation guide that would be great!

**Comment by alasdairwilson** [comment]
You might want a compose file to make it easier to deploy the container (as some compose-style deployment stuff is in the fly.toml). A compose file would only make it more general.

**Comment by alasdairwilson** [comment]
I think this is closed by #115 #93 blog.oxrse.uk/gutenberg/deployment  for the outcome of these prs

feel free to make new issues or reopen if you want changes.
