### ISSUE TITLE
More responsive material pages web layout

### ISSUE THREAD

**Issue by steve-crouch** [OxfordRSE/gutenberg#58]
Would it make sense to have a more responsive web layout for material pages, where the content width resizes proportionally to the browser width? This may make sense for learners (and those delivering instructor-led sessions) with larger monitors.

**Comment by martinjrobins** [comment]
We use the TailwindCSS "prose" styling, which is specifically aimed at producing readable text generated from markdown.

 I do find text more readable when the lines arn't too long, and so am not a fan of resizing the lines to match screen width (I favor the latex approach of short fixed textwidth)

**Comment by martinjrobins** [comment]
https://tailwindcss.com/docs/typography-plugin

**Comment by steve-crouch** [comment]
As discussed, we'll leave this as is.
