### ISSUE TITLE
Render bullet-pointed list of material on main material overview page

### ISSUE THREAD

**Issue by steve-crouch** [OxfordRSE/gutenberg#62]
On the materials overall page, below the diagram it might be useful to have the materials rendered as a bullet point-style list (e.g. by module/lesson) which links to the modules/lessons in the material. This may become more important as more material is added to ease navigation.

**Comment by martinjrobins** [comment]
Hi Steve, we've redone the main materials page to remove the diagram and just provide a list of themes, does this work better?

https://train.oxrse.uk/material

**Comment by steve-crouch** [comment]
This looks great - much easier to traverse! We also discussed the possibility of having a high-level diagram 
 that just shows relationships between modules, as a possible "nice to have".
