### ISSUE TITLE
Nested solution blocks

### ISSUE THREAD

**Issue by fcooper8472** [OxfordRSE/gutenberg#7]
@martinjrobins looking here:
https://gutenberg.fly.dev/material/software_architecture_and_design/object_orientated/classes

First challenge has two solution blocks, and the second one doesn't display anything when opened.

Do you see this behaviour too?

**Comment by martinjrobins** [comment]
yup, I've fixed this by separating them into two solutions blocks rather than nested in https://github.com/OxfordRSE/gutenberg/commit/bf2a15c02dcecd7cb8acf1247555a98f7db14e96 . Thanks @fcooper8472
