### ISSUE TITLE
Change topbar nav to burger menu on small screens

### ISSUE THREAD

**Issue by alasdairwilson** [OxfordRSE/gutenberg#74]
When you go deep down a material tree the navbar gets destroyed on mobile devices, we should make it collapse on small screens, rprobably keep the right hand side icons but make the material nav into a burger menu

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/8e8b63c8-f10c-4c7f-9b79-a39758072e56)

**Comment by dankimberley** [comment]
implemented by #235
