### ISSUE TITLE
get a minimal list (or project board) of issues todo before a release

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#75]
My goal for gutenberg is for a teaching platform that all RSE groups can use, so it would be good to identify what remains todo before we can start letting other groups know about it and hopefully get feedback / users

- [x] Templatise site-specific pages #59 
- [x] Deployment docs #57
- [x] bug #89 
- [x] delete event #50

**Comment by alasdairwilson** [comment]
#104
