### ISSUE TITLE
better enrollment workflow

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#88]
Its really annoying to have to approve enrollments as they come in (especially as you tell all the students to enroll before the start of the course, but then they all enroll in a trickle over the first 2 days of the course), I wonder if there is a better way to do this, but I can't currently think of one......

**Comment by alasdairwilson** [comment]
I was gonna add an enrolment key. Can be handed out to students prior to course starting or just verbally in the course etc. Can probably sort it pretty quickly, don't think it requires much work.

**Comment by martinjrobins** [comment]
yes! an enrolment key we can hand out / email to all the students on the course would be great!, thanks @alasdairwilson. Perhaps have different enrolment keys for students and instructors as well?
